version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: psd_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psd_colab
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d psd_colab"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: psd_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    command: ["node","dist/index.js"]

volumes:
  pgdata:
